name: Generate & Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docs Docker image
        run: docker build -t docs_generator -f docs_generator/Dockerfile .

      - name: Generate docs
        run: |
          mkdir -p docs
          docker run --rm \
            -v ${PWD}/alerts_service:/app/src/alerts_service:ro \
            -v ${PWD}/analytics_service:/app/src/analytics_service:ro \
            -v ${PWD}/collector_service:/app/src/collector_service:ro \
            -v ${PWD}/flask_api:/app/src/flask_api:ro \
            -v ${PWD}/sensor_script.py:/app/src/sensor_script.py:ro \
            -v ${PWD}/docs:/app/output \
            docs_generator

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs